version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-3001}:${PORT:-3000}"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ferreteria-network

  mongodb:
    image: mongo:7.0.5
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - ferreteria-network
    profiles:
      - dev

networks:
  ferreteria-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 