version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/ferreteria
      - JWT_SECRET=your_jwt_secret
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ferreteria-network

  mongodb:
    image: mongo:7.0.5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ferreteria
      # Configuración de autenticación (recomendado para producción)
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=your_secure_password
    command: mongod --auth --bind_ip_all
    restart: unless-stopped
    networks:
      - ferreteria-network
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  ferreteria-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/ferreteria/mongodb_data
      o: bind 