version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/ferreteria
      - JWT_SECRET=your_jwt_secret
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ferreteria-network

  mongodb:
    image: mongo:7.0.5
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - ferreteria-network

networks:
  ferreteria-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 